services:
  webserver:
    build:
      context: .
      dockerfile: frankenphp/Dockerfile
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      # Uncomment this to configure the server name for Xdebug, default is localhost
      # PHP_IDE_CONFIG: 'serverName=localhost'
      DATABASE_CONNECTION: ${DB_CONNECTION:-pgsql}
      DATABASE_HOST: ${DB_HOST:-database}
      DATABASE_PORT: ${DB_PORT:-5432}
      DATABASE_DATABASE: ${DB_DATABASE:-app}
      DATABASE_USERNAME: ${DB_USERNAME:-app}
      DATABASE_PASSWORD: ${DB_PASSWORD:-!ChangeMe!}
    ports:
      # Node.js
      - "3000:3000"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
    depends_on:
      database:
        condition: service_healthy
      minio:
        condition: service_healthy

  database:
    volumes:
      - ./postgresql/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  minio:
    build:
      context: .
      dockerfile: minio/Dockerfile
    container_name: "minio"
    restart: unless-stopped
    ports:
      - "8090:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
      MINIO_VOLUME: /data
    volumes:
      - minio_data:/data
    tty: true

volumes:
  database_data:
  minio_data:
